# Description: # Chem 274B: Software Engineering Fundamentals for
#               Molecular Sciences
# Final project :  Design and C++ Implementation of General Purpose
#                 Cellular Automata Library. 
# Team members: Sheyda Nazarian, Yingyin Yu,Jedrick Regala Zablan 
# Date Created: 12/1/2023 
# Path: ./Application
  
APP_UTILS_DIR = Utils/           
APP_DATA_DIR = Data/
APP_BIN_DIR = Bin/

all:
	cd $(APP_UTILS_DIR); make all
	cd $(APP_BIN_DIR); make all
	cd $(APP_DATA_DIR); make all

cleanall:	
	cd $(APP_UTILS_DIR); make cleanall
