# Description: # Chem 274B: Software Engineering Fundamentals for
#               Molecular Sciences
# Final project :  Design and C++ Implementation of General Purpose
#                 Cellular Automata Library. 
# Team members: Sheyda Nazarian, Yingyin Yu,Jedrick Regala Zablan 
# Date Created: 12/1/2023 
# Path: ./Utils
           
DATA_DIR = Data/

all:
	cd $(DATA_DIR); make all

cleanall:	
	cd $(DATA_DIR); rm Data_test_localized_init/*.txt
